### ISSUE TITLE
Turbo-Range-Coder

### ISSUE THREAD

**Issue by powturbo** [tongdaxu/YAECL-Yet-Another-Entropy-Coding-Library#1]
Hi,
there is a now an adaptive rANS implementation in [Turbo-Range-Coder](https://github.com/powturbo/Turbo-Range-Coder).
Turbo-Range-Coder is supporting 8/16/32 bits  integer / float. Differencial / zigzag / gamma / rice / TurboVLc coding / Context mixing / bwt....

**Comment by tongdaxu** [comment]
Hi, thanks for providing this resources. I am aware of this repo and I have already cited it in the readme.

**Comment by powturbo** [comment]
Yes thank you, but rANS is new in the latest version and not available in your table.

**Comment by tongdaxu** [comment]
Oh I see, you have rANS now. I will add it to readme.
